### ISSUE TITLE
Please provide a rationale for 'open' Client ID

### ISSUE THREAD

**Issue by mimi89999** [benbucksch/mauth-spec#3]
Hello,
In 3.2 there is the following sentence:
> The server MUST accept the following Client ID (RFC 6749 2.2): open

Could you please explain why the string `open` was chosen? It would also be nice to assess how this can interfere with current setups that might already use that name for other purposes.

**Comment by benbucksch** [comment]
> Could you please explain why the string `open` was chosen?

I first called it `mail`, but we also want to allow calendar and chat. `open` is a generic term.

The other alternative would be to call it `mAuth`.
